---
title: "Homework 4 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    course_code: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(p8105.datasets)
library(plotly)
```

```{r import ,include=FALSE}
data("ny_noaa")

noaa_clean <- ny_noaa %>% 
  filter(grepl("2000",as.character(date))) %>% 
  separate(date, sep="-", into = c("year","month","day")) %>% 
  mutate(
        year = as.numeric(year), month = as.numeric(month), day = as.numeric(day),
        prcp = as.integer(round(prcp*.1*0.03937008)),
        snow = as.integer(round(snow*0.03937008)),
        snwd = as.integer(round(snwd*0.03937008)),
        tmax = as.integer(round(as.numeric(tmax)*.1*1.8+32)),
        tmin = as.integer(round(as.numeric(tmin)*.1*1.8+32))
         )

```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatter plot of min and max temperatures (F) for all stations in 2000

```{r scatter}
noaa_clean %>%
  mutate(text_label = str_c("ID: ", id, "\nMonth: ", month, "\nDay", day)) %>% 
  plot_ly(
    x = ~tmin, y = ~tmax, type = "scatter", mode = "markers",
    color = ~month, text = ~text_label, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Violin plot of seasonal max temperature (F) for all stations in 2000

```{r violin}
noaa_clean %>% 
  mutate(season = case_when(between(month,3,5) ~ "Spring",
                            between(month,6,8) ~ "Summer",
                            between(month,9,11) ~ "Fall",
                            between(month,1,2) | month == 12 ~ "Winter"),
         season = fct_relevel(as.factor(season),c("Spring", "Summer", "Fall", "Winter"))) %>% 
  plot_ly(x = ~season, y = ~tmax, color = ~season, type = "violin", colors = "viridis")
```

### Bar plot of monthly mean precipitation in inches for all stations in 2000

```{r bar}
noaa_clean %>% 
  group_by(month) %>% 
  summarise(mean_prcp=mean(prcp, na.rm = TRUE)) %>% 
  plot_ly(x = ~month, y = ~mean_prcp, color = ~month, type = "bar", colors = "viridis")
```

