---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

making some plotly plots!

## load packages and data

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

let's get some data.

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    borough=neighbourhood_group, neighbourhood, rating, price, room_type, lat, long,rating) %>%
  filter(
    !is.na(rating), 
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500) %>% 
  drop_na(rating)

```

let's make a scatterplot

```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating,"\nNeighbourhood: ",neighbourhood)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

can we make boxplots?? yep

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

can we make a barplot?? yep

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")

```

## ggplotly

```{r}
scatter_ggplot = 
  nyc_airbnb %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```


## create a dashboard

not here though, it's standalone
